
services:
  - type: web
    name: iac-2d-pro
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    autoDeploy: true
    envVars:
      - key: GOOGLE_API_KEY
        value: ""
